$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
environment: azureml:python-base-nfs:1
compute: azureml:cpu-cluster
code: code/
command: |
  mkdir /data
  mount -t nfs 10.0.2.4:/amlnfs/amlnfsshare /data -o vers=4,minorversion=1,sec=sys
  df -h
  python train.py

  echo "Write NFS test"
  time dd if=/dev/zero of=/data/testfile bs=16k count=400k
  
  echo "Read NFS test"
  time dd if=/data/testfile of=/dev/null bs=16k
  
  
  mkdir /test
  
  echo "Write local test"
  time dd if=/dev/zero of=/test/testfile bs=16k count=400k
  
  echo "Read local test"
  time dd if=/test/testfile of=/dev/null bs=16k
  
  
  
  
  
  
  
